---
- name: Update Pi-hole Gravity
  hosts: piholes
  become: yes
  serial: 1
  
  tasks:
    - name: Update Pi-hole Gravity list
      command: pihole -g
      register: gravity_update_output

    - name: Display Pi-hole Gravity update output
      debug:
        var: gravity_update_output.stdout_lines
