---
- name: Reboot Linux Servers
  hosts: servers
  become: yes
  tasks:
    - name: Gather facts
      setup:

    - name: Reboot servers
      reboot:
        post_reboot_delay: 150

    - name: Check if SSH is back online after reboot
      wait_for:
        host: "{{ inventory_hostname }}"
        port: 22
        state: started
        delay: 30
        timeout: 300
