---
- name: Update and Reboot Servers
  hosts: servers
  become: yes
  tasks:

    - name: Update package lists
      apt:
        update_cache: yes
      when: ansible_os_family == "Debian"

    - name: Upgrade all packages
      apt:
        upgrade: dist
      when: ansible_os_family == "Debian"

    - name: Check if reboot is required
      stat:
        path: /var/run/reboot-required
      register: reboot_required

    - name: Display if reboot is required
      debug:
        msg: "Reboot required!"
      when: reboot_required.stat.exists

    - name: Reboot servers if required
      reboot:
        post_reboot_delay: 150
      when: reboot_required.stat.exists
