---
- name: Update and Reboot Linux Servers if Required
  hosts: servers
  become: yes
  serial: 5  # Reboot five servers at a time
  tasks:
    - name: Gather facts
      setup:

    - name: Update package lists (Debian)
      apt:
        update_cache: yes
      when: ansible_os_family == "Debian"

    - name: Upgrade all packages (Debian)
      apt:
        upgrade: dist
      when: ansible_os_family == "Debian"

    - name: Autoremove unnecessary packages (Debian)
      apt:
        autoremove: yes
      when: ansible_os_family == "Debian"

    - name: Reboot servers
      reboot:
        post_reboot_delay: 15
      
    - name: Check if SSH is back online after reboot
      wait_for:
        host: "{{ inventory_hostname }}"
        port: 22
        state: started
        delay: 30
        timeout: 420
